sudo: required

dist: trusty

language: cpp

compiler:
    - gcc
    #- clang

addons:
    apt:
        packages:
            - libboost-all-dev
            - libcrypto++-dev

script: cd build && cmake ../ && make

notifications:
    email: false
