env:
  global:
  - GCC_VERSION=5
  - FORCE_CLEAN=yes
  - FORCE_INSTALL=yes
sudo: required
dist: trusty
language: cpp
compiler:
- gcc
addons:
  apt:
    packages:
    - gcc-5
    - g++-5
    - libcrypto++-dev
    - libssl-dev
    - libssl1.0.0
    - libminiupnpc-dev
    - doxygen
    sources:
    - ubuntu-toolchain-r-test
before_install:
- git submodule update --init --recursive
- sudo add-apt-repository -y ppa:kojoley/boost
- sudo apt-get -q update
- sudo apt-get -y install libboost-{chrono,log,program-options,date-time,thread,system,filesystem,regex,test}1.58{-dev,.0}
before_script: export CC=gcc-${GCC_VERSION} CXX=g++-${GCC_VERSION}
script: make clean && make -j2 dependencies && make -j2 all-options && make -j2 tests && make doxygen && make install-resources && ./kovri-tests && ./kovri-benchmarks
notifications:
  email: false
  irc:
    on_success: change
    on_failure: change
    channels:
      - "chat.freenode.net#kovri-dev"
    nick: kovri
    template:
      - "%{result} | %{repository}#%{build_number} (%{commit} : %{author}) | Build details : %{build_url}"
