sudo: required
dist: trusty
language: cpp

compiler:
    - gcc
    # Uncomment when we can actually build with clang
    #- clang

addons:
    apt:
        packages:
            - libboost-all-dev
            - libcrypto++-dev

script: cd build && cmake ../ && make

notifications:
    email: false
    #irc: "chat.freenode.net#kovri-dev"
    #nick: kovri-ci
    #password:
